language: go

go_import_path: https://github.com/wavefronthq/opencensus-exporter

go:
  - 1.9.x
  - 1.11.x
  - 1.12.x
 
env:
  global:
    GO111MODULE=on

script:
  - go vet ./...
  - go test -v ./...
  - go test -timeout 10m -v -race ./...
